# Generated by Django 5.0.2 on 2024-02-16 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning_logs', '0002_entry'),
    ]

    operations = [
        migrations.RenameField(
            model_name='topic',
            old_name='date_ended',
            new_name='date_added',
        ),
    ]
